name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cat ~/GH_TOKEN.txt | docker login -u dungducphan --password-stdin
        docker tag IMAGE_ID docker.pkg.github.com/dungducphan/dockersqltool-imagerepo/sqlviewer:latest
        docker push docker.pkg.github.com/dungducphan/dockersqltool-imagerepo/sqlviewer:latest
